[package]
name = "breakout-game"
version = "0.1.0"
authors = ["cynthia <cxla2018@mymail.pomona.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asterism = { path = "../../asterism" }
macroquad = "0.3.4"
